const tableData = [
  {
    id: 1,
    clientId: "2030",
    name: "Merkur - Xtip",
    link: "https://drVerify Eye.google.com/file/d/15wOdDJtm_96bL_tv0ly0CeYC5djhaSjP/view?usp=drive_link",
    createdAt: "2023-05-28",
    services: ["AutoIdent", "Neos", "Fintec"],
    serviceInitial: ["Auto Ident", "N E", "Fin Tech"],
    country: "Italy",
    logo: "/logos/Xtip.jpg",
  },
  {
    id: 2,
    clientId: "2031",
    name: "Merkur - Cashpoint",
    link: "https://drive.google.com/file/d/1yMZoAEBz8mgabQgRrAZeK2RZglmx4yFJ/view?usp=sharing",
    createdAt: "2023-05-28",
    services: ["AutoIdent", "Neos", "Fintec"],
    serviceInitial: ["Auto Ident", "N E", "Fin Tech"],
    country: "Germany",
    logo: "/logos/cashpoint.png",
  },
  {
    id: 3,
    clientId: "2032",
    name: "Merkur - Casino",
    link: "https://drive.google.com/file/d/1GR9LnjvGO9iz5sZiK0sQgfvkm8BZ4UfD/view?usp=sharing",
    createdAt: "2023-05-28",
    services: ["AutoIdent", "Neos", "Fintec"],
    serviceInitial: ["Auto Ident", "N E", "Fin Tech"],
    country: "Germany",
    logo: "/logos/merkur.webp",
  },
  {
    id: 4,
    clientId: "2030",
    name: "Merkur - Spiel",
    link: "https://drive.google.com/file/d/1se5TCBWGJwLmWAnGK0vbZKWaVoKDvcIA/view?usp=sharing",
    createdAt: "2023-05-28",
    services: ["AutoIdent", "Neos", "Fintec"],
    serviceInitial: ["Auto Ident", "N E", "Fin Tech"],
    country: "Austria",
    logo: "/logos/spiel.webp",
  },
  {
    id: 5,
    clientId: "2003",
    name: "Tiptoro",
    link: "https://gitlab.mgt.eu/mgt-client-config/configuration-ui",
    createdAt: "2023-04-11",
    services: ["PostIdent", "Hooyu", "WebIdSign"],
    serviceInitial: ["Post Ident", "Hoo Yu", "WebId Sign"],
    country: "Italy",
    logo: "/logos/tiptorro.jpg",
  },
  {
    id: 6,
    clientId: "2004",
    name: "Betway",
    link: "https://gitlab.mgt.eu/mgt-client-config/configuration-ui",
    createdAt: "2023-03-15",
    services: ["Jumio", "Neos", "Identt"],
    serviceInitial: ["Joo U", "N E", "Identt"],
    country: "Germany",
    logo: "/logos/betway.png",
  },
  {
    id: 7,
    clientId: "2005",
    name: "Lowenplay",
    link: "https://gitlab.mgt.eu/mgt-client-config/configuration-ui",
    createdAt: "2023-06-22",
    services: ["Neos", "Hooyu", "Jumio"],
    serviceInitial: ["N E", "Hoo Yu", "Joo U"],
    country: "Germany",
    logo: "/logos/lowenplay.jpg",
  },
  {
    id: 8,
    clientId: "2008",
    name: "Sportwetten",
    link: "https://gitlab.mgt.eu/mgt-client-config/configuration-ui",
    createdAt: "2022-01-21",
    services: ["PostIdent", "WebId", "WebIdSign"],
    serviceInitial: ["Post Ident", "Web Id", "WebId Sign"],
    country: "Austria",
    logo: "/logos/sportwetten.png",
  },
  {
    id: 9,
    clientId: "2011",
    name: "Gluecksfall",
    link: "https://gitlab.mgt.eu/mgt-client-config/configuration-ui",
    createdAt: "2021-06-14",
    services: ["Jumio", "Identt", "WebIdSign"],
    serviceInitial: ["Joo U", "Identt", "WebId Sign"],
    country: "Austria",
    logo: "/logos/Gluecksfall.png",
  },
  {
    id: 10,
    clientId: "2014",
    name: "red Rhino",
    link: "https://gitlab.mgt.eu/mgt-client-config/configuration-ui",
    createdAt: "2022-08-16",
    services: ["WebId", "WebIdSign"],
    serviceInitial: ["Web Id", "WebId Sign"],
    country: "Austria",
    logo: "/logos/redrhino.png",
  },
];

const serviceColors = {
  "Auto Ident": "#FE7046",
  "N E": "#114780",
  "Fin Tech": "#0065AF",
  "Verify Eye": "#5BBBC1",
  "Hoo Yu": "#E89456",
  "WebId Sign": "#05B8FF",
  "Joo U": "#92C038",
  "In Ventia": "#C83240",
  "Identt": "#C83240",
  "Post Ident": "#FDCA3F",
  "Web Id": "#05B8FF",
};

const selectServiceItems = [
  { label: "Identt", value: "Identt", key: "Identt" },
  { label: "Hooyu", value: "Hooyu", key: "Hooyu" },
  // { label: "Verifeye", value: "Verifeye", key: "Verifeye" },
  { label: "AutoIdent", value: "AutoIdent", key: "AutoIdent" },
  { label: "PostIdent", value: "PostIdent", key: "PostIdent" },
  { label: "Authada", value: "Authada", key: "Authada" },
  { label: "Fintec", value: "Fintec", key: "Fintec" },
  { label: "Jumio", value: "Jumio", key: "Jumio" },
  { label: "ATrust", value: "ATrust", key: "ATrust" },
  { label: "WebId", value: "WebId", key: "WebId" },
  { label: "WebIdSign", value: "WebIdSign", key: "WebIdSign" },
  { label: "IdAustria", value: "IdAustria", key: "IdAustria" },
  { label: "Neos", value: "Neos", key: "Neos" },
  { label: "ItsMe", value: "ItsMe", key: "ItsMe" },
];

const selectEnvironmentItems = [
  { label: "Local", value: "Local", key: "Local" },
  { label: "Demo", value: "Demo", key: "Demo" },
  { label: "Production", value: "Production", key: "Production" },
];

export { serviceColors, tableData, selectServiceItems, selectEnvironmentItems };
